name: Bug report
description: Something's broken or returning wrong results
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report this.

  - type: input
    id: version
    attributes:
      label: griptape-mcp version
      placeholder: "0.1.0  (run: pip show griptape-mcp)"
    validations:
      required: true

  - type: input
    id: client
    attributes:
      label: MCP client
      placeholder: "Claude Desktop / Claude Code / other"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you ask, what did the AI say or do, what went wrong?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: dropdown
    id: tool
    attributes:
      label: Which tool was involved? (if known)
      options:
        - search_docs
        - get_page
        - search_griptape_nodes
        - get_node_details
        - list_categories
        - get_code_examples
        - Not sure / general
