name: Feature request
description: Suggest a new tool, data source, or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you running into?
      description: Describe the workflow where griptape-mcp currently falls short.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - New MCP tool
        - More documentation coverage
        - Search quality improvement
        - Performance
        - Docker / deployment
        - Developer experience
        - Other
